language: go

sudo: required

services:
  - docker

go:
  - 1.10.x
  - master

matrix:
  allow_failures:
  - go: master
  fast_finish: true

install:
  - make install

script:
  - make test
  - make check-api
  - make test-e2e
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
