language: go

go:
  - 1.10.x
  
before_install:
  - go get gortc.io/api
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install

install: true

script:
  - ./go.test.sh
  - make check-api
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)