language: go

go:
  - 1.10.x
  - master

matrix:
  allow_failures:
  - go: master
  fast_finish: true

before_install:
  - make install

install: true

script:
  - ./go.test.sh
  - make check-api
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
